service:
    port: 1001
    redis:
        host: 'redis'
        port: 6379
shops:
    - apodiscounter:
        url: http://www.apodiscounter.de/partnerprogramme/krn.csv
        config:        
            header: 1
            delimeter: 59 # ; char
            endline: "\n"
            columns:
                id: 0
                price: 1
    - eurapon:
        url: http://preisexporte.apobyte.de/www.eurapon.de/preissuchmaschine/preissuchmaschine.csv
        config:        
            header: 1
            delimeter: 9 # Tab char
            endline: "\r\n"
            columns:
                id: 0
                price: 3